### ISSUE TITLE
Info panel does not display

### ISSUE THREAD

**Issue by gohma231** [hermanho/MMM-GooglePhotos#110]
Hello,

I have images displaying flawlessly, but the info panel is not being displayed. Any help would be appreciated.

What I've tried:

## 1.
```
#GPHOTO_INFO {
    top: 100px;
    left: 1000px;
    bottom: inherit;
    right: inherit;
  }
  ```
The above text moved a small black bubble into the frame (not the dimensions as shown in the github screenshots). This does not resolve the issue. 

## 2. Enable Debug

This does not resolve the issue either. The photos index as they should. 

## 3. Check photoListCache.json

creationTime and _albumID are populated.

**Comment by aneaville** [comment]
Did the info show up before adding the #GPHOTO_INFO to your custom.css? The offsets you added of 100 and 1000 may be off the screen. Have you tried:(to show in top left corner)
#GPHOTO_INFO {
    top: 10px;
    left: 10px;
    bottom: inherit;
    right: inherit;
  }

Do you have the 'autoInfoPosition' enabled of disabled?

Since something did show up, I suspect is 'working' but not quite as expected(captain obvious right....). Do you mind sharing your config, I'll use the same settings to see if I get the same results.

**Comment by gohma231** [comment]
The info never showed up. I also tried 10px. I tried both true and false
for autoInfoPosition. I'll share my config later tonight

**Comment by gohma231** [comment]
Here is my `config.js`. My `custom.css` is currently empty.

https://pastebin.com/y5Cw3jxc

**Comment by aneaville** [comment]
I used your config and it worked fine. I'm suspecting that the resolution might be off and putting the info off screen. What kind of monitor are you using?
Some things to try:
1. Can you try to use the autoInfoPosition? This will change the corner every quarter of the hour. ex, at 8:15, 8:30, 8:45 ....
2. Instead of waiting for this to change, you could add the following to your custom.css 1 by 1 and see if any show up appropriately
#GPHOTO_INFO {
top: 10px;
left: 10px;
bottom: none;
right: none;
}
#GPHOTO_INFO {
top: none;
left: 10px;
bottom: 10px;
right: none;
}
#GPHOTO_INFO {
top: none;
left: none;
bottom: 10px;
right: 10px;
}
#GPHOTO_INFO {
top: 10px;
left: none;
bottom: none;
right: 10px;
}

Lastly, when you did see a bubble, what did you mean by "not the dimensions as shown in the github screenshots"? was it smaller or larger? or too small to see?

**Comment by aneaville** [comment]
no response for a long time. I'm going to close the issue. If you would still like assistance, feel free to reopen. Thanks.
