### ISSUE TITLE
Google photos album repeats the same photos in a day

### ISSUE THREAD

**Issue by bhaules** [hermanho/MMM-GooglePhotos#114]
I have an album with about 5k photos and during a day it seems I’m only seeing 20 or so photos that repeat themselves over and over. The photos used to be more random in the past but not sure what is happening now that they are repeating so much. Any ideas why? Anything I can do to clear the cache somehow and let it start rebuilding it?
Thank you for this beautiful module. My wife and kids love it!

**Comment by aneaville** [comment]
It sounds like there are errors, and it is defaulting to just show the latest 20 pictures. 

First thing I wonder is if you are resetting regularly or not. I think most people automatically reset daily.

2nd thing I would recommend is to turn on debugging by adding "debug: true," to your config. This will show more information, and would help point to the issue. I don't leave it on by default because it makes the logs balloon up quicker. If you can share the log when this issue is happening, I could probably help more.

**Comment by bhaules** [comment]
Thank you for being so helpful.
I had a look in the magic mirror logs and they got really big so I removed them and started fresh. 
I had MagicMirror restart every hour as in the past it used to stay on a photo indefinitely. Now I'm only restarting it once a day. I'll see how that goes. It already seems better but after the hourly restart there are a lot of the previous photos. Maybe that's how it's written do display some of the cached photos until it fully loads all of them.

Thanks
