### ISSUE TITLE
Storing Google photos locally to minimize Internet bandwidth ??

### ISSUE THREAD

**Issue by kootch** [hermanho/MMM-GooglePhotos#13]
Sorry, this is not an issue rather a feature question/request.  Is there any way to store the photos from Google Drive locally to minimize Internet traffic?  
I am building a pi_mirror for someone with limited bandwidth and it would be best to check for new photos in the album, download those to a local storage (partition or usb flash) and rotate/display images from that location on the Magic Mirror.  This would limit Internet calls for each album update and image url.  It may also reduce problems with number of API calls (could just update once or twice a day to get any new images).
I could probably spin off a new fork, but I wanted to see if anyone has already invented this wheel.
Thanks, Pete

**Comment by eouia** [comment]
Good approach. But downloaded photos might take a huge volume of storage.
When photos are not so much, Just use other module which handles local photos. There are several modules already.

**Comment by kootch** [comment]
Thank you for your reply. I'd still want it to use Google Photos as it is a great way to share family photos to multiple geographically located Magic Mirrors.  I thought about the storage problem.  My approach would devise a way to only retain a limited number of photos in storage by deleting the oldest during the update process. For example, if there are two new photos in the google album since the last update, and I am at my limit in the local store (say 20 photos), delete the two oldest and add the two newest.  You can also loop through the array of mediaItems and if the filename already exists locally, skip saving it (lowers bandwidth and no need to download again).  Just an idea...thoughts?

**Comment by ShakirAkbari** [comment]
smart caching would be beneficial and have a similar affect. the approach would be to download if not in the cache - that way you can allot any amount of cache space and if the cache is full then the photo would be downloaded. & instead of being too smart about clearing the cache - just clearing it every x days / hours would be sufficient for the vast majority of the time. 


this would be a huge benefit for me - specifically because this magic mirror is going to be about 7500 miles away from me.

**Comment by eouia** [comment]
Well...
1) At start, Get all filenames(only filename) and store them as an index of photos.
2) Select 20 Photos from the index (by random or sequence)
3) Get their temporal URL by API query. Because, GP's url would be changed in short time - in 1hour. So URL should be queried at the moment as close before downloaded.
4) Download and store. 
5) If downloaded files are over 100, remove older files.
5-1) Or stop download and reuse already downloaded. (This could save network transfer and API quota). After some time(or after days? or after new photos detected) repeat newly from 1 again. 
6) After first photo be downloaded, Show them one-by-one. 
7) When All 20 photos are downloaded, repeat 2-5 again
8) To detect new photos, repeat 1 periodically.

Right?

**Comment by ShakirAkbari** [comment]
Yes this sounds right to me. 

Regarding 5.1 - I would do a full refresh after a configurable amount of time (personally I would set it to once per week). But new photos should be added to the slide show as they appear (when they are not in the index (or array) of photos).

Regarding 5: I think having configurable value the number of photos which can be stored is a good idea since it should make it easier to code for - that way you would not need to do the math on the storage.

**Comment by eouia** [comment]
I’ll consider. However it could be a new module with new structure.

**Comment by kootch** [comment]
Thanks for all of the ideas.  For my purpose, I am thinking a 20 photo limit, check daily for any new uploads, grab new and swap out oldest if more than 20 in "memory".  Cache may be a good idea, but would they have to be downloaded after a reboot or power loss?

I'll add more more feature that would be nice to have at some time.  Google Photos allows you to add a photo description.  In my proposed shared family album and network of interlinked mirrors, it would be nice to display the description under the photo as a caption to tell the viewer a little about the photo.  I have successfully added mediaItem.description to the getPhotosByAlbumId function, but I'm still learning how to pass that to the getPhoto function and manipulate the DOM and display the description to the GooglePhotos DIV.  Still tinkering with it......
Nice module @eouia, thanks!

**Comment by kootch** [comment]
@eouia No, I have not started a new fork.  Just playing with the code locally, so please proceed.  I didn't want to burden anyone else with my desired enhancements, but if you feel they would be good for the evolution of your module I would greatly appreciate leaning on your programing knowledge and experience with the MM architecture.  Thank You!

**Comment by dlurk97** [comment]
I would love to have this functionality. Besides bandwidth concerns, I think it might help my issue of photos not loading quickly enough causing a "jerky fade"...

**Comment by eouia** [comment]
@dlurk97 Yes. I'm working now. Plz wait a few days.

**Comment by eouia** [comment]
I abandon this improvement. Sorry I was too busy and lost my interesting about this issue. If who can make PR about this, gladly I’ll accept.
