### ISSUE TITLE
Scanning does not complete

### ISSUE THREAD

**Issue by keremsevimli** [hermanho/MMM-GooglePhotos#17]
The module is scanning all over again:
```
pi@raspberrypi:~/MagicMirror $ DISPLAY=:0 npm start
>magicmirror@2.7.1 start /home/pi/MagicMirror
>sh run-start.sh
Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-GooglePhotos
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-GooglePhotos
MMM-GooglePhotos started
Sockets connected & modules started ...
Launching application.
MMM-GooglePhotos initialized after loading.
[GPHOTO] Scan finished : 123
[GPHOTO] Scan finished : 123
```

**Comment by eouia** [comment]
On Each Scan finished message, 1 cycle of scanning be finished.
Google will chang url of image periodically, so rescanning before url dying is needed.

**Comment by keremsevimli** [comment]
But Magic mirror is not starting (no show up)?

**Comment by eouia** [comment]
I'm not sure what your issue is.
Log says nothing wrong. If nothing is shown up, It might be due to my module or not, but the more information is needed.
First, Remove or comment out other modules and leave only MMM-GooglePhotos then run MM again. Still the problem?
Second, If you have still got problem, Frontend-log is needed to figure out what was happening. you can get frontend log by `Ctrl+shift+i` on MM screen or starting with `npm start dev` instead `pm2`

**Comment by keremsevimli** [comment]
Yes, you are right! It was not an issue from the module. I do not know why it did not show up.
