### ISSUE TITLE
This app isn't verified

### ISSUE THREAD

**Issue by matelot20** [hermanho/MMM-GooglePhotos#74]
Follow the instructions and going through Google API console. Goto "Enable APIs & Services", select "Photos Library API". Goto Credentials and create credentials. Select OAuth Client ID. Next screen select "Other" as application type. Google displays client ID strings and client secret code.
Goto "OAuth consent screen" and enter "MagicMirror" in app name and support email. Click on Save.
Download the key, rename to credentials.json and run node generate_token.js. After clicking on my email account, I get This App isn't verified.  I've done this multiple times even creating a new OAuth client IDs.

Can you help?

**Comment by eouia** [comment]
First, Even Unverified App(yours) could be usable as a devloping/testing. To verily, you should open the app publicly, but it might be not your intention.
When you meet alert page on consent, just ignore the warning of unverified. process further. Because this app is used only for you, so verification by Google is not needed.

**Comment by matelot20** [comment]
When you say open the app publicly, you mean "magicmirror" and not Google Photos?

**Comment by matelot20** [comment]
It works by going through another link to "Advanced". I was able to get the code. Thanks for your response.
