### ISSUE TITLE
Request: specify multiple albums

### ISSUE THREAD

**Issue by mdissel** [hermanho/MMM-GooglePhotos#8]
Feature request: specify multiple albums id's in the config and fetch the photos from all the specified albums.. 
Thanks!

**Comment by eouia** [comment]
Thanks for your suggestion. I'll consider it.
By the way, There could be a risk of API being exhausted too fast if multi album scanning would be supported. GooglePhoto API quota is not so enough subtly. Due to restriction of API, this module is  consuming API quota inefficiently. 
I think better approach is, make a new album for your featured photos to be displayed, not entire photos.

**Comment by mdissel** [comment]
>  There could be a risk of API being exhausted too fast if multi album scanning would be supported.

But the limit is:
>The quota limit for requests to the Library API is 10,000 requests per project per day

If we fetch the content of the album once every x hours/day? And include a filter to only return mediatype photo...

**Comment by eouia** [comment]
Url is temporary, (max 1 hour as documented - but sometimes seems exhausted sooner)
So too long term dosn’t make sense.
I think Without random sorting, less scanning capable, but for random, unusung scanning somehow be needed.
I’ll research more.

**Comment by mdissel** [comment]
See #9
