### ISSUE TITLE
Portrait photo as dual

### ISSUE THREAD

**Issue by river350** [hermanho/MMM-GooglePhotos#88]
This module replaced chromecast for showing photos in living room.

The only thing I miss from chromecast is dual portrait photos to get less blurr picture. 

Hope this is something you can include 👌

**Comment by ChrisAcrobat** [comment]
I think you can solve this by some custom CSS. See https://github.com/ChrisAcrobat/MMM-GooglePhotos#tip

**Comment by aneaville** [comment]
This would be a feature request. To elaborate some more, on Chromecast, when the screen is horizontal, rather than showing a single vertical picture, it will show 2 vertical side by side. Further more, the chromecast is usually smart enough to not show random pictures, but usually pictures that are related. Either the same people, or same location, etc.

Although I like the idea, the framework used here is not easily modified to fit this. It could be done, but I'm not willing to make these changes. If someone wants to tackle it, I would be happy to provide some guidance. Given this has been here for over a year though, I'm going to close this.
